django_openedu/edu_data/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'edu_data'  # to differentiate in the html the application used in the urls
urlpatterns = [
    path('', views.edumaterial_list_view, name='home_page'),
    path('<int:id>', views.detail_page, name='detail'),  # path for going to the detail view
    #path('search/', views.search_filter, name='search'),  # names need to match the ones in the html to reference url
    path('search/', views.search_NLP, name='search')  # names need to match the ones in the html to reference url
]

django_openedu/edu_data/templates/edumaterial/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Home page</title>
  </head>
  <body>
    <div class="text-center jumbotron">
        <h1>OPENEDU</h1>
    </div>
    <hr>
    <div class="container">
         <!-- add the search button-->
        <form action="{% url 'edu_data:search' %}" method="get" ALIGN='center'> <!--class="form-inline"-->
            <div class="form-group mx-sm-3 mb-2">
                <label for="" class="sr-only">search</label>
                <input name="search" type="" class="form-control" id="" placeholder="type for search">
            </div>
            <div class="form-group col-md-4">
                <label for="category">Category</label>
                <select id="category" class="form-control" name="category">
                  <option selected>Choose...</option>
                  {% for cat in categories %}
                    <option name="{{ cat.categories }}" value="{{ cat.pk }}">{{ cat.categories }}</option>
                  {% endfor %}
                </select>
            </div>
                <div class="form-group col-md-4">
                <label for="materialformat">Material type</label>
                <select id="materialformat" class="form-control" name="materialformat">
                  <option selected>Choose...</option>
                  {% for format in formats %}
                    <option name="{{ format.name }}" value="{{ format.pk }}">{{ format.name }}</option>
                  {% endfor %}
                </select>
            </div>

            <button type="submit" class="btn btn-primary btn-lg mb-2">search</button>
        </form>
    </div>
    <hr>

    <div class="container">
        <!-- include container to display the list of educational material-->
        <main>
        <h1> These are the OpenEdu entries: </h1>
        <!-- include the data by referencing the context variable in django as bellow inside -->
        {% for material in edu_materials%}
            <!-- the <a> is included for creating the link. In this case the id of the object needs to be passed to the
            url, which is going to be used in the view of the detail page-->
            <a href = "{%url 'edu_data:detail' material.id %}"><h1>{{material.title|title}}</h1></a>
            <p>{{material.description|truncatewords:40}}</p> <hr> <!-- the hr puts the line after the entries -->
        {% endfor %}
        </main>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

django_openedu/edu_data/templates/edumaterial/home_old.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Home page</title>
  </head>
  <body>
    <div class="text-center jumbotron">
        <h1>OPENEDU</h1>
    </div>
    <hr>
    <div class="container">
         <!-- add the search button-->
        <form action="{% url 'edu_data:search' %}"  method="get" ALIGN='center'> <!--class="form-inline"-->
            <div class="form-group mx-sm-3 mb-2">
                <label for="" class="sr-only">search</label>
                <input name="search" type="" class="form-control" id="" placeholder="type for search">
            </div>
            <button type="submit" class="btn btn-primary btn-lg mb-2">search</button>
        </form>

        <!-- include container to display the list of educational material-->
        <main>
        <h1> These are the OpenEdu entries: </h1>
        <!-- include the data by referencing the context variable in django as bellow inside -->
        {% for material in edu_materials%}
            <!-- the <a> is included for creating the link. In this case the id of the object needs to be passed to the
            url, which is going to be used in the view of the detail page-->
            <a href = "{%url 'edu_data:detail' material.id %}"><h1>{{material.title|title}}</h1></a>
            <p>{{material.description|truncatewords:40}}</p> <hr> <!-- the hr puts the line after the entries -->
        {% endfor %}
        </main>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

django_openedu/edu_data/templates/edumaterial/search.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Home page</title>
  </head>
  <body>
    <div class="text-center jumbotron">
        <h1>OPENEDU</h1>
    </div>
    <div class="container">
        {% if query %} <!-- if there is a return query from the search, a match-->
        <h1>Projects containing "{{ query }}"</h1>
           <h3>
             {% with results.count as total_results %} <!--this returns the total of results-->
                Found {{ total_results }} result{{ total_results|pluralize }}
             {% endwith %}
           </h3>
           {% for c in results %}
              <a href="{{c.get_absolute_url}}"><h3>{{c.title}}</h3></a> <!--get absolute url is a function of the class-->
              <p>{{c.description|truncatewords:40}}</p> <hr> <!-- the hr puts the line after the entries -->
              {% empty %}
              <h4>There are no results for your query.</h4>
           {% endfor %}
        {% else %}
            <h2>NO QUERY  ERROR </h2>
        {% endif %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>